version: '3.4'
services:
  cv:
    build:
      context: ./cloudvolume
      dockerfile: cloudvolume.dockerfile
    volumes:
      -  ${CVDATA}:/mnt/data:ro
    ports:
      - 1337:1337
  nglancer:
    build:
      context: ./neuroglancer
      dockerfile: neuroglancer.dockerfile
    depends_on:
      - cv
    ports:
      - 8080:8080
