version: '3.4'
services:
  cv:
    build:
      context: ./cloudvolume
      dockerfile: cloudvolume.dockerfile
    volumes:
      #- "cv-root:/mnt/data:ro"
      -  ${CVDATA}:/mnt/data:ro
  nglancer:
    build:
      context: ./neuroglancer
      dockerfile: neuroglancer.dockerfile

#volumes:
#  cv-root:
#    name: ${CVDATA}
#    external: false
